"""empty message

Revision ID: 603814508f54
Revises: e53227f76752
Create Date: 2023-10-11 21:42:06.911471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603814508f54'
down_revision = 'e53227f76752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['professor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('professor_id')

    op.drop_table('user')
    # ### end Alembic commands ###
