"""empty message

Revision ID: 64fe0918d5c4
Revises: 603814508f54
Create Date: 2023-10-11 22:10:05.206278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fe0918d5c4'
down_revision = '603814508f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['professor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('professor_id')

    # ### end Alembic commands ###
