"""empty message

Revision ID: 94412d8cb206
Revises: 6845617bc15f
Create Date: 2023-10-11 22:56:49.243530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94412d8cb206'
down_revision = '6845617bc15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('professor_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('professor_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
