"""empty message

Revision ID: d6510429ef51
Revises: 94412d8cb206
Create Date: 2023-10-12 02:29:52.148645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6510429ef51'
down_revision = '94412d8cb206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=200), server_default='1', nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
