"""empty message

Revision ID: e53227f76752
Revises: c57a554a1d88
Create Date: 2023-09-06 22:38:03.620795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53227f76752'
down_revision = 'c57a554a1d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_attendance',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_check_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_check_id'], ['attendance_check.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'attendance_check_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_attendance')
    op.drop_table('attendance_check')
    # ### end Alembic commands ###
